<a href="https://colab.research.google.com/github/Solrak97/clasificador_de_sentimientos/blob/main/Random_forest_speech_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Busqueda de entradas para el modelo base propuesto por Dias Issa et al.
El modelo base cuenta con una entrada de 193 nodos, por lo que es necesario que cada entrada de datos tenga exactamente 193 variables, eso a partir de las ya conocidas caracteristicas 

* Chromagram
* Contrast
* Mel coeficent
* Mel frequency
* Tonnetz

### Descarga de los datos desde Kaggle hasta el notebook.

In [ ]:
!pip show pandas

Name: pandas
Version: 1.3.5
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: https://pandas.pydata.org
Author: The Pandas Development Team
Author-email: pandas-dev@python.org
License: BSD-3-Clause
Location: /usr/local/lib/python3.7/dist-packages
Requires: numpy, python-dateutil, pytz
Required-by: xarray, vega-datasets, statsmodels, sklearn-pandas, seaborn, pymc3, plotnine, pandas-profiling, pandas-gbq, pandas-datareader, mlxtend, mizani, holoviews, gspread-dataframe, google-colab, fix-yahoo-finance, fbprophet, fastai, cufflinks, cmdstanpy, arviz, altair


In [1]:
%%capture
! pip install kaggle wavio pydub keras-metrics

#! rm -rf *
#! mkdir ~/.kaggle
#! curl https://raw.githubusercontent.com/Solrak97/clasificador_de_sentimientos/main/kaggle.json > kaggle.json
#! cp kaggle.json ~/.kaggle/
#! chmod 600 ~/.kaggle/kaggle.json
#! kaggle datasets download uwrfkaggler/ravdess-emotional-speech-audio
#! unzip ravdess-emotional-speech-audio.zip
#%%capture
! curl https://raw.githubusercontent.com/Solrak97/clasificador_de_sentimientos/main/data.pkl > data.pkl

import soundfile
import numpy as np
import pandas as pd
import librosa
import glob
import os
import pickle
from pydub import AudioSegment
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_pickle('data.pkl')
data.head(3)

ValueError: ignored

In [ ]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# Building X
X = np.array([np.hstack([data['Duration'][i], data['MFCC'][i], data['Chroma'][i], data['Mel'][i], 
                         data['Contrast'][i], data['Tonnetz'][i]]) for i in range(len(data.index))])
scaler = StandardScaler()
scaler.fit(X)
X = scaler.transform(X)

# Building X
Y = np.array(data['Emotion'])

# Building the Training and Test sets
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2)

# Applying One-Hot-Encoder to test sets
encoder = OneHotEncoder()
y_train_1HE = encoder.fit_transform(np.array(y_train).reshape(-1,1)).toarray()
y_test_1HE = encoder.fit_transform(np.array(y_test).reshape(-1,1)).toarray()

print(f'''
  X_train: {X_train.shape}
  X_test: {X_test.shape}
  y_train: {y_train.shape}
  y_test: {y_test.shape}
  y_train_1HE: {y_train_1HE.shape}
  y_test_1HE: {y_test_1HE.shape}
''')

print(y_train_1HE)




NameError: ignored

### Algoritmo de extracción de datos

RANDOM FOREST

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

print(y_train_1HE.shape)
classifier = RandomForestClassifier(n_estimators = 100, random_state = 0)
classifier.fit(X_train, y_train_1HE)
predicted = classifier.predict(X_test)

c = 0
for row in predicted:
  print(row)
  c=+1
print(c)
print(accuracy_score(y_true=y_test_1HE, y_pred=predicted))
print(classification_report(y_test_1HE, predicted))
print(confusion_matrix(y_test, predicted))

(1152, 8)
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 1.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0.]
[0

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


ValueError: ignored

In [ ]:
c_p_shape = predicted.shape
print(c_p_shape)

class_pred = []
for row in range(c_p_shape[0]):
  act_row = []
  for col in range(c_p_shape[1]):
    act_row.append(predicted[row][col])
  c_predicted = np.argmax(act_row)
  class_pred.append(c_predicted)
  print(act_row)
print(f'\nClases predichas\n{class_pred}')

#print(c_p_shape)

c_pred = np.argmax(predicted)

print(c_pred)


(288, 8)
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
[0.0, 0

In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

classifier = RandomForestClassifier(n_estimators = 20, random_state = 0)
classifier.fit(X_train, y_train)
c_p = classifier.predict(X_test)
print(accuracy_score(y_true=y_test, y_pred=c_p))
print(classification_report(y_test, c_p))
print(confusion_matrix(y_test, c_p))

0.1423611111111111
              precision    recall  f1-score   support

           0       0.92      0.34      0.50        35
           1       0.73      0.48      0.58        33
           2       1.00      0.04      0.07        52
           3       1.00      0.06      0.11        36
           4       1.00      0.06      0.11        35
           5       0.00      0.00      0.00        23
           6       0.00      0.00      0.00        46
           7       1.00      0.25      0.40        28

   micro avg       0.85      0.14      0.24       288
   macro avg       0.71      0.15      0.22       288
weighted avg       0.72      0.14      0.21       288
 samples avg       0.14      0.14      0.14       288



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


ValueError: ignored

Precision 0.7 (100 estimators) y 0.647 (20 estimators)

Emociones consideradas: neutral, calm, happy, sad, angry, fearful, disgust y surprised.

Features consideradas: mfcc, chroma, mel, contrast y tonnetz.


Considerando solo mfcc, chorma y mel con las mismas emociones: 0.7 y 0.7

Considerando solo las emociones angry, sad, neutral y happy con los features mfcc, chroma, mel, contrast y tonnetz: 0.9 y 0.9

Considerando solo las emociones angry, sad, neutral y happy con los features mfcc, chroma y mel: 0.9 y 0.8

Parece que disminución de emociones y aumento de features aumentan precisión.